Vagrant.configure(2) do |config|


  config.vm.box = "debian/jessie64"

  config.vm.network "public_network", ip: "192.168.0.18"

  config.vm.provision "shell", path: "./provision/init.sh"
  config.vm.synced_folder ".", "/vagrant", disabled: true


  #Configuracion de ejemplo para vagrant-unificar
  #OBLIGATORIO - Path del directorio en el host a montar en la virtual
  #Puede ser absoluto o relativo
  #config.unificar.local_dir = "."

  #OBLIGATORIO - Path absoluto del punto de montaje en la virtual
  #config.unificar.remote_mountpoint = "/vagrant"

  #OPCIONAL - Ip del host
  #Si no es especificado, utiliza la ip por defecto: 10.0.2.2
  #config.unificar.host_ip = "10.6.1.78"

  #OPCIONAL - Muestra el comando ejecutado en la consola
  #Cuidado que muestra el password despues de ser tecleado
  #config.unificar.debug = true
end
